### ISSUE TITLE
Why are 2D coordinates reversed in `add_coordinates`?

### ISSUE THREAD

**Issue by freemansw1** [climate-processes/tobac#123]
I noticed this weekend that the 2D coordinate order was reversed in `add_coordinates`, e.g.,:
https://github.com/climate-processes/tobac/blob/0d098acfaad0dd5e8ac9e07bed13c3e01d42a2a8/tobac/utils.py#L386-L388

I'm not sure why this is the case, although it seems like the results are correct? What is the reason for this, and does it matter?

**Comment by JuliaKukulies** [comment]
Is it maybe because `scipy.interpolate.interp2d()` wants the coordinates in x,y order which corresponds to y=rows = 1st dimension of the iris cube coordinates and x = columns = 2nd dimension of the iris cube coordinates? This always confuses me a lot. But I think it looks like that, so when the array with 2D latlon coordinates has a different order than they are ordered in the iris cube `if variable_cube.coord_dims(coord) == (hdim_2, hdim_1):`, they would already be in the right x-y order and are not swapped. In contrast `if variable_cube.coord_dims(coord) == (hdim_1, hdim_2): `,  they need to be swapped to keep the right x-y order?

**Comment by zxdawn** [comment]
Agree with @JuliaKukulies. If we can switch to xarray totally in the future, it would be easier to use `.interp()` of xarray.

**Comment by freemansw1** [comment]
I think I understand this now and I'm on board. Thanks @JuliaKukulies! We're wrapping up some of our 3D code, and actually what brought this up was looking at `scipy.interpolate.interpn()`, which doesn't seem to require this "backwards" indexing? Their documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html#scipy.interpolate.interpn) seems to suggest that if the `values` array is in y, x coordinates, the `points` array also must be `y, x`.

**Comment by freemansw1** [comment]
And totally agreed @zxdawn, xarray makes this substantially easier. Once 1.5 is out, I think `xarray` will be a primary focus as we get closer to 2.0.
