### ISSUE TITLE
Harmonize distance parameters in tracking functions 

### ISSUE THREAD

**Issue by freemansw1** [climate-processes/tobac#63]
The presence of `v_max`, `d_min`, and `d_max` are confusing in the tracking functions at this point. We need to improve both the documentation here and how tobac rectifies these three functions. Some of this has been resolved in `v2.0-dev`, but even there it is still a little confusing. 

I've looked over the code and this is my understanding of the three parameters:

`v_max`: the maximum velocity (in units of `dxy`/`dt`) that an object can move between frames/timesteps
`d_max`: the maximum distance (in the same units as `dxy`) that an object can move between frames/timesteps
`d_min`: the minimum distance; overwrites `v_max` or `d_max`. 

So, here's my proposal:
- Ultimately get rid of two of these (I think we should keep `v_max`) as they all do the same thing and overwrite each other. 
- Throw a deprecation warning now for the two we will ultimately get rid of but keep behavior the same for now. In the documentation, strongly encourage users to use whichever one is picked and state something to the effect of "do not use xx". 
- Throw a warning now if users are using any more than one of these at a time. 
- Eventually (v2 or later perhaps?), throw an error when using the two that are depreciated

Unfortunately, I'm hesitant to break compatibility with existing code now, but I think we have a path forward.

**Comment by w-k-jones** [comment]
Personally I'm happy to keep both v_ and d_max, as although they overwrite each other one may be more useful than the other for the user. However, this does highlight several related issues:

1. If both v_max and d_max are set, which should be used? I would argue that which gives the smallest limit on motion should be used, rather than simply always overwriting 1 with the other
2. If we keep both v_max and d_max, then it would make sense to also have a v_min
3. d_min, v_min shouldn't overwrite d_max/v_max, but instead set a minimum bound on the motion. i.e. if both d_max and d_min are set, then objects can only be selected that move greater than d_min and less than d_max. I'm not sure how this works with trackpy however.

**Comment by freemansw1** [comment]
This has been resolved by #107.
