### ISSUE TITLE
How to set dynamic multi-thresholds for tracking?

### ISSUE THREAD

**Issue by zxdawn** [climate-processes/tobac#77]
Usually, we can set multi-thresholds for tracking. However, sometimes the thresholds can be dynamic.

For example, there're two data that are the same variable on different days.
The boundaries of the high spots are 0.9e-5 and -0.1e-5, respectively. The differences in boundary values can be even larger.

![image](https://user-images.githubusercontent.com/30388627/155698730-68b3b7c2-899a-495f-8c98-75cbe6140a5a.png)

Is it possible to calculate suitable multi-thresholds automatically for different days' data?

Because I want to get the boundary of every high spots, setting the max of multi-thresholds to the highest one will only detect the inner part of high spots which has lower values.

I have tried to use the histogram for selecting thresholds, but the number of high spots can be large or small. I can't figure out the right way.

**Comment by zxdawn** [comment]
I will appreciate it a lot if you have any ideas! @mheikenfeld @w-k-jones @JuliaKukulies @deeplycloudy

**Comment by JuliaKukulies** [comment]
I think the issue with a dynamical threshold is an important and good point you are raising (if I understand the problem correctly) and maybe worth to think about to implement as an additional feature user can choose. 

What you describe is probably applicable to other problems as well. A similar problem could be that you want to use the same tracking method for an inter-model comparison on a variable (say outgoing longwave radiation) whose distribution looks significantly different in different models. 

What exactly did you do with the histograms @zxdawn ? Would it be meaningful to maybe check the tails of your distribution in each day (e.g. 5th and 95th percentile) and then scale the values according to the percentiles in a reference day, where you know the suitable threshold, so you can use the same threshold for all days? 

Alternatively, you could perform a daily feature detection and choose the thresholds in each day based on the histogram of the same day, instead of correcting the input fields. Or is that what you already tried? I did not understand why this would not work, because when you use the daily histograms, it should not matter if your extreme values for the day are not extreme in the histogram for the entire dataset? Correct me if I am wrong :)

**Comment by zxdawn** [comment]
@JuliaKukulies You got my point! I tried the daily percentile method. However, the percentile depends on the number of large values. 95% should work well for a few large values, but if the number of large values occupies more than 20% of total pixels, then the percentile should be changed to < 80%. If I understand correctly, the scaling method also won't consider the number correctly.

**Comment by freemansw1** [comment]
I think what @JuliaKukulies suggests second in her comment is the cleanest way. My suggestion, within the existing frame of *tobac*, is to run feature detection independently on each day and/or frame, varying the thresholds that you choose. You could also normalize the data (and clip values above a certain threshold), running feature detection on the new normalized data.

I think this kind of thing is something we really need to consider as we advance *tobac* into the future. New methods of feature detection could examine this, certainly.

**Comment by zxdawn** [comment]
@freemansw1 Thanks! The normalization is a good point. I will test some cases.

**Comment by zxdawn** [comment]
Finally, I came up with this solution based on your suggestions.

Normalize the data (which have both negative and positive values) --> Fit the lognorm function and set the max value with alpha=0.2 as the `min_threshold` --> generate the threshold with 10 steps from `min_threshold` to 1 --> run the segmentation

Here's result:
![image](https://user-images.githubusercontent.com/30388627/160202743-5d78293b-6196-406f-88ad-1c63c6568d40.png)
![image](https://user-images.githubusercontent.com/30388627/160202792-5ae55f41-3841-4323-b560-007434f53d44.png)

**Comment by freemansw1** [comment]
It looks like this question has been answered, so I'm going to close this for now. Feel free to reopen if you want to continue the discussion!
