### ISSUE TITLE
Difference between 'identified features' and 'tracked features'

### ISSUE THREAD

**Issue by zxdawn** [climate-processes/tobac#8]
I've tried this example with different thresholds: *tobac/examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb*
`parameters_features['threshold']=[250]` and 
`parameters_features['threshold']=[150]`.

Here's my result:
**250:**
![250](https://user-images.githubusercontent.com/30388627/50594625-47182400-0ed8-11e9-9a20-4dcedff80a70.png)
**150**:
![150](https://user-images.githubusercontent.com/30388627/50594647-5dbe7b00-0ed8-11e9-8609-bc83b0d9e256.png)

1. I'm confused of the color of outline:
https://github.com/climate-processes/tobac/blob/3c8abdf86f26b7a77f1143e05ee4bd1adc2f48a4/tobac/plotting.py#L136
What's the meaning of each color?

2. I'm not familiar with **watershed** and **trackpy** and still learning it.
It looks like the region blocks are meticulous when the value is close to the threshold, rough when the value is far from the threshold. 
I guess it's related to the function of **parameters_features['position_threshold']**, **watershed** and **trackpy**, especially the difference between **identified features** and **tracked features**.
Could you explain it briefly?
How to choose the list of threshold to make the result meet user's own demand?

**Comment by zxdawn** [comment]
After watching and reading tutorials, I understand **watershed** better now.

For questions above, here's my answer:

1. The color of marker depends on the amount of cells in that area generated by marker and watershed.

2. I'm still trying to find the suitable parameters to track the local minimum. Here's an [example notebook](https://github.com/zxdawn/tobac/blob/xin/examples/Example_OLR_Tracking_satellite/Example_TBB_Tracking_satellite.ipynb). It seems it works better for regions which have smaller minimum ...

**Comment by mheikenfeld** [comment]
A quick answer to you questions, thanks for your interest in using tobac. I'm sorry for the confusion due to the currently rather marginal documentation, we'll make sure to provide some proper documentation, especially regarding the individual parameters very soon and are about to submit a publication giving more details about the package!

1. The colour of the marker and the outline is a random choice from a few manually defined colors in different shades of red and orange. It basically just serves to distinguish visually between the individual tracked cells. Cells in grey are those that have only been picked up in individual time steps but were not connected  up into a successful trajectory.

2. The choice of the parameters is obviously usually the tricky thing. The package allow to set the parameters as a range of values as in our example notebooks e.g.

`parameters_features['threshold']=[250,225,200,175,150]`

Which will use the range of values in a stepwise procedure, maybe that can also help in your use case.

**Comment by mheikenfeld** [comment]
Sorry, just saw your question about **identified features** and **tracked features** so a few more words regarding my answer to question 1: This is related to the two individual steps that we perform in the analysis and probably a bit of uncelar wording in the comments. At each timestep features are detected (grey and colourful ones in the plots above), which are objects identified at an individual proint in time. Then some of those will be linked into trajectories in the linking step (which gives the ones plotted in color above)
